In [181]:
import sage.libs.lrcalc.lrcalc as lrcalc
import numpy as np
import functools

In [190]:
def lamsComp(lams,a,b):
    
    #     :param lams: an array of partitions
    #     :param    a: number of rows
    #     :param    b: number of columns
    #     :return    : complement of lams under rectangle a*b

    result = []
    
    for lam in lams:
        comp = []
        for i in range(a):
            if i >= len(lam):
                comp = [b]*(a-i) + comp
                break
            if (b-lam[i]) == 0: continue
            comp.insert(0,b-lam[i])
            
        result.append(comp)
    
    return result

In [182]:
def NL(l,mu):
    n_l = sum(l)
    n_mu = sum(mu)
    
    listAlphaBeta = []

    for i in range(0,n_l+1):
        for a in Partitions(i).list():
            for b in Partitions(n_l-i).list():
                if lrcalc.lrcoef(l, a, b) != 0:
                    listAlphaBeta.append([a,b])
    listabg = []
    for i,ab in enumerate(listAlphaBeta):
        n_beta = sum(ab[1])
        b = ab[1]
        for g in Partitions(n_mu - n_beta).list():
            if lrcalc.lrcoef(mu,b,g) != 0:
                listabg.append(ab+[g])
#     nu = []
    nuDict = {}
    for abg in listabg:
        a = abg[0]
        g = abg[2]
        n_a = sum(a)
        n_g = sum(g)
        for v in Partitions(n_a+n_g).list():
            if lrcalc.lrcoef(v, a, g) != 0:
#                 if v not in nu:
#                     nu.append(v)
                v = Partition(v)
                if v not in nuDict:
                    nuDict[v] = [abg]
                else:
                    nuDict[v].append(abg)
    for v in nuDict:
        currentNL = 0
        for abg in nuDict[v]:
            a = abg[0]
            b = abg[1]
            g = abg[2]
#             print(v, a, b, g)
            currentNL += lrcalc.lrcoef(l,a,b) * lrcalc.lrcoef(mu,b,g) * lrcalc.lrcoef(v,g,a)
        nuDict[v] = currentNL
        
    return nuDict

In [186]:
def lexOrder(l1,l2):
    # if l1 < l2, return negative
    
    n_l1 = len(l1)
    n_l2 = len(l2)
    
    if n_l1 < n_l2:
        l1 = l1 + ([0]*(n_l2-n_l1))
    if n_l2 < n_l1:
        l2 = l2 + ([0]*(n_l1-n_l2))
    
    for i,e in enumerate(l1):
        if e == l2[i]:
            continue
        if e < l2[i]:
            return -1
        if e > l2[i]:
            return 1
    return 0

In [192]:
lams3

[[], [1], [1, 1], [1, 1, 1], [2], [2, 1], [2, 1, 1], [2, 2], [3], [3, 1]]

In [188]:
lams3.sort(key=functools.cmp_to_key(lexOrder))

In [191]:
lams3C

[[3, 3, 3],
 [3, 3, 2],
 [3, 3, 1],
 [3, 2, 2],
 [3, 3],
 [3, 2, 1],
 [2, 2, 2],
 [3, 2],
 [3, 1, 1],
 [2, 2, 1]]

In [155]:
lams2 = [[], [1], [2], [1, 1]]
lams2C = [[2, 2], [2, 1], [2], [1, 1]]

In [149]:
lams4 = [[], [1], [2], [1, 1], [3], [2, 1], [1, 1, 1], [4], [3, 1], [2, 2], [2, 1, 1], [1, 1, 1, 1], [4, 1], [3, 2], [3, 1, 1], [2, 2, 1], [2, 1, 1, 1], [4, 2], [4, 1, 1], [3, 3], [3, 2, 1], [3, 1, 1, 1], [2, 2, 2], [2, 2, 1, 1], [4, 3], [4, 2, 1], [4, 1, 1, 1], [3, 3, 1], [3, 2, 2], [3, 2, 1, 1], [2, 2, 2, 1], [4, 4], [4, 3, 1], [4, 2, 2], [4, 2, 1, 1], [3, 3, 1, 1], [3, 2, 2, 1], [2, 2, 2, 2]]
lams4C = [[4, 4, 4, 4], [4, 4, 4, 3], [4, 4, 4, 2], [4, 4, 3, 3], [4, 4, 4, 1], [4, 4, 3, 2], [4, 3, 3, 3], [4, 4, 4], [4, 4, 3, 1], [4, 4, 2, 2], [4, 3, 3, 2], [3, 3, 3, 3], [4, 4, 3], [4, 4, 2, 1], [4, 3, 3, 1], [4, 3, 2, 2], [3, 3, 3, 2], [4, 4, 2], [4, 3, 3], [4, 4, 1, 1], [4, 3, 2, 1], [3, 3, 3, 1], [4, 2, 2, 2], [3, 3, 2, 2], [4, 4, 1], [4, 3, 2], [3, 3, 3], [4, 3, 1, 1], [4, 2, 2, 1], [3, 3, 2, 1], [3, 2, 2, 2], [4, 4], [4, 3, 1], [4, 2, 2], [3, 3, 2], [3, 3, 1, 1], [3, 2, 2, 1], [2, 2, 2, 2]]

In [166]:
lams = lams4
lamsC = lams4C
indList = []
vectors = []
markNew = []

for i,l in enumerate(lams):
    lC = lamsC[i]
    current = NL(l,lC)
    if i == 0:
        indList = [v for v in current]
        currentV = [0]*1000
        for v in current:
            currentV[indList.index(v)] = current[v]
        vectors.append(currentV)
    else:
        currentV = [0]*1000
        for v in current:
            if v not in indList:
                markNew.append(Partition(l))
                indList.append(v)
            currentV[indList.index(v)] = current[v]
        vectors.append(currentV)


maxInd = np.max(np.nonzero(vectors[-1]))
vectors = np.array(vectors)
vectors = vectors[:,0:int(maxInd)+1]

print("===")
vectors = [list(v) for v in vectors]
print(np.array(vectors))

===
[[1 0 0 ... 0 0 0]
 [1 1 1 ... 0 0 0]
 [1 2 1 ... 0 0 0]
 ...
 [1 4 4 ... 1 0 0]
 [1 7 7 ... 0 1 0]
 [1 1 1 ... 0 0 1]]


In [169]:
set([Partition(l) for l in lams]) - set(markNew)

{[], [4, 1, 1, 1], [4, 2, 1, 1]}

In [159]:
A = span(vectors,ZZ)
print(A.dimension() == len(vectors))

True


In [161]:
lams3

[[], [1], [2], [1, 1], [3], [2, 1], [1, 1, 1], [3, 1], [2, 2], [2, 1, 1]]

In [15]:
lrcalc.lrcoef([5,4,3,3,2,2,1],[5,4,3,3],[2,2,1])

1

In [106]:
l = [2]
lC = [2]
n_l = sum(l)
n_lC = sum(lC)


In [107]:
listAlphaBeta = []

for i in range(0,n_l+1):
    for a in Partitions(i).list():
        for b in Partitions(n_l-i).list():
            if lrcalc.lrcoef(l, a, b) != 0:
                listAlphaBeta.append([a,b])

In [108]:
listAlphaBeta

[[[], [2]], [[1], [1]], [[2], []]]

In [109]:
listabg = []
for i,ab in enumerate(listAlphaBeta):
    n_beta = sum(ab[1])
    b = ab[1]
    for g in Partitions(n_lC - n_beta).list():
        if lrcalc.lrcoef(lC,b,g) != 0:
            listabg.append(ab+[g])

In [110]:
listabg

[[[], [2], []], [[1], [1], [1]], [[2], [], [2]]]

In [111]:
nu = []
for abg in listabg:
    a = abg[0]
    g = abg[2]
    n_a = sum(a)
    n_g = sum(g)
    for v in Partitions(n_a+n_g).list():
        if lrcalc.lrcoef(v, a, g) != 0:
            if v not in nu:
                nu.append(abg+[v])

In [112]:
nu

[[[], [2], [], []],
 [[1], [1], [1], [2]],
 [[1], [1], [1], [1, 1]],
 [[2], [], [2], [4]],
 [[2], [], [2], [3, 1]],
 [[2], [], [2], [2, 2]]]

In [90]:
print(NL([2],[2]), "\n", NL([1,1],[1,1]), "\n", NL([2,1],[1]), "\n", NL([2,2],[]))

[[], [2], [1, 1], [4], [3, 1], [2, 2]] 
 [[], [2], [1, 1], [2, 2], [2, 1, 1], [1, 1, 1, 1]] 
 [[2], [1, 1], [3, 1], [2, 2], [2, 1, 1]] 
 [[2, 2]]


In [78]:
nu

[[], [2], [1, 1], [4], [3, 1], [2, 2]]

In [113]:
lams3 = [[], [1], [2], [1, 1], [3], [2, 1], [1, 1, 1], [3, 1], [2, 2], [2, 1, 1]]
lams3C = [[3, 3, 3], [3, 3, 2], [3, 3, 1], [3, 2, 2], [3, 3], [3, 2, 1], [2, 2, 2], [3, 2], [3, 1, 1], [2, 2, 1]]

In [114]:
for i,l in enumerate(lams3):
    print(NL(l, lams3C[i]))

[[3, 3, 3]]
[[3, 3, 1], [3, 2, 2], [4, 3, 2], [3, 3, 3], [3, 3, 2, 1]]
[[3, 2], [3, 1, 1], [4, 3], [3, 3, 1], [4, 2, 1], [3, 2, 2], [3, 2, 1, 1], [5, 3, 1], [4, 3, 2], [4, 3, 1, 1], [3, 3, 3], [3, 3, 2, 1]]
[[3, 1, 1], [2, 2, 1], [4, 2, 1], [3, 3, 1], [3, 2, 2], [3, 2, 1, 1], [2, 2, 2, 1], [4, 3, 2], [4, 2, 2, 1], [3, 3, 3], [3, 3, 2, 1], [3, 2, 2, 1, 1]]
[[3], [4, 1], [3, 2], [3, 1, 1], [5, 2], [4, 3], [4, 2, 1], [3, 3, 1], [3, 2, 2], [6, 3], [5, 3, 1], [4, 3, 2], [3, 3, 3]]
[[3], [2, 1], [1, 1, 1], [4, 1], [3, 2], [3, 1, 1], [2, 2, 1], [2, 1, 1, 1], [5, 2], [4, 3], [4, 2, 1], [3, 3, 1], [3, 2, 2], [5, 1, 1], [4, 1, 1, 1], [3, 2, 1, 1], [2, 2, 2, 1], [3, 1, 1, 1, 1], [2, 2, 1, 1, 1], [5, 3, 1], [5, 2, 2], [5, 2, 1, 1], [4, 4, 1], [4, 3, 2], [4, 3, 1, 1], [4, 2, 2, 1], [4, 2, 1, 1, 1], [3, 3, 3], [3, 3, 2, 1], [3, 3, 1, 1, 1], [3, 2, 2, 2], [3, 2, 2, 1, 1]]
[[1, 1, 1], [3, 1, 1], [2, 2, 1], [2, 1, 1, 1], [3, 3, 1], [3, 2, 2], [3, 2, 1, 1], [2, 2, 2, 1], [2, 2, 1, 1, 1], [3, 3, 3], [3, 